// src/components/Header.vue
<script setup>

/*
import { ref } from 'vue'

defineProps({
  msg: String,
})

const count = ref(0)
*/

/*
<h1>{{ msg }}</h1>

  <div class="card">
    <button type="button" @click="count++">count is {{ count }}</button>
    <p>
      Edit
      <code>components/HelloWorld.vue</code> to test HMR
    </p>
  </div>
*/
</script>

<template>
  <header>
    <a href="/" id="logo"></a>
    <h1>Cuerviar</h1>
    <div class="redesSociales">
      <a href="https://www.youtube.com/@cuerviar-dev" target=" _blank" id="youtube"></a>
    </div>
    <nav class="enlacesPc">
      <RouterLink to="/">Inicio</RouterLink>
      <RouterLink to="/ubuntu">Ubuntu</RouterLink>
      <RouterLink to="/programas">Programas</RouterLink>
      <RouterLink to="/windows10">Windows 10</RouterLink>
    </nav>
  </header>
</template>

<style scoped>
header {
  background-color: #0D0D1A;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-around;
  align-items: center;
  padding: 1rem 0;
}

h1 {
  color: white;
}

#logo {
  display: block;
  width: 5rem;
  height: 5rem;
  background-image: url("/cuervo.svg");
  background-position: center;
  background-size: contain;
  background-repeat: no-repeat;
}

header a {
  text-decoration: none;
  color: white;
}

header .enlacesPc {
  width: 100%;
  display: flex;
  justify-content: space-evenly;
  list-style: none;
}

header .enlacesPc li {
  margin-right: 2rem;
}

header .enlacesPc li:last-child {
  margin-right: 0;
}

#youtube {
  display: block;
  width: 4rem;
  height: 2rem;
  background-image: url("/youtube.svg");
  background-position: center;
  background-size: contain;
  background-repeat: no-repeat;
}
</style>

// src/components/Header.jsx
import IconButton from './IconButton'

import { useContext, useState } from "react"
import { ThemeContext } from "../ThemeContext"

export default function App() {
    const { toggleTheme, theme } = useContext(ThemeContext);
    const [isNavOpen, setIsNavOpen] = useState(false);

    const openNav = () => {
        setIsNavOpen(true);
    }


    const closeNav = () => {
        setIsNavOpen(false);
    }

    const headerStyle = {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        transition: 'all .3s ease-in-out',
        padding: '0 3%',
    }

    const logoStyle = {
        display: 'block',
        width: '3rem',
        height: '3rem',
        backgroundImage: `url(${theme == 'light' ? './cuervo-light.svg' : './cuervo-dark.svg'})`,
        cursor: 'pointer',
        userSelect: 'none',
        transition: 'all .3s ease-in-out',
        backgroundPosition: 'center',
        backgroundSize: '80% 80%',
        backgroundRepeat: 'no-repeat',
    }

    const iconsButtonsStyle = {
        display: 'flex',
    }

    const navStyle = {
        position: 'fixed',
        left: `${isNavOpen ? '0' : '-100%'}`,
        top: '0',
        width: '100%',
        height: '100vh',
        backgroundColor: `${theme == 'light' ? '#f8fafc' : '#09090b'}`,
        transition: 'all .3s ease-in-out',
    }

    const ulStyle = {
        height: '100%',
        listStyleType: 'none',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'space-evenly'
    }

    const liStyle = {
    }

    const routeStyle = {
        textDecoration: 'none',
        color: `${theme == 'light' ? '#334155' : '#FFFFFF'}`,
        userSelect: 'none',
    }

    return (
        <>
            <header style={headerStyle}>
                <a href='/' style={logoStyle} onClick={(e) => { e.preventDefault() }} />
                <div style={iconsButtonsStyle}>
                    <a href="https://www.youtube.com/@cuerviar-dev" target=" _blank">
                        <IconButton iconLight={"./youtube-light.svg"} iconDark={"./youtube-dark.svg"} />
                    </a>
                    <IconButton onClick={toggleTheme} iconLight={"./sun.svg"} iconDark={"./moon.svg"} />
                    <IconButton onClick={openNav} iconLight={"./menu-light.svg"} iconDark={"./menu-dark.svg"} />
                </div>
            </header>
            <nav style={navStyle} onClick={closeNav}>
                <ul style={ulStyle}>
                    <li style={liStyle}><a style={routeStyle} href='/' onClick={(e) => { e.preventDefault() }}>Inicio</a></li>
                    <li style={liStyle}><a style={routeStyle} href='/Debian' onClick={(e) => { e.preventDefault() }}>Debian</a></li>
                    <li style={liStyle}><a style={routeStyle} href='/Windows10' onClick={(e) => { e.preventDefault() }}>Windows 10</a></li>
                </ul>
            </nav>
        </>
    )
}
